### ISSUE TITLE
Partial view table sample (5 lines)

### ISSUE THREAD

**Issue by csychester** [imulus/TableEditor#19]
Hi, a great plugin and edition to Umbraco.

Is it possible have a partial view that only outputs the first 5 rows of the table body <tr> so I could output a sample of the table rather than the full table? My razor abilities are limited to monkey see monkey do, could you point me in the right direction.

Thanks

Neil

**Comment by kgiszewski** [comment]
if you are using the sample template from the project homepage...

```
@foreach (var row in Model.Cells.Take(5))
{}
```

Mileage may vary.

**Comment by csychester** [comment]
Thank you..works well
